Author:- **Bhautik Gondaliya**

mo. no.:- **[9586280240](https://)**

mail id.:- **[mr.genius0180@gmail.com](https://)**
>
>
guide:- **Shivam Mishra**

Sponcerd:- **Intellipaat**
>
>
Title:- **Module-8 Assignments**

Date:- **8/11/2024**

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, accuracy_score, confusion_matrix

# **Linear Regression Model**

In [4]:
df = pd.read_csv("data.csv")
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [5]:
df.shape

(30, 2)

In [6]:
x, y = df.iloc[:, [0]], df.iloc[:, 1]

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

In [9]:
linear_model.fit(x_train, y_train)

LinearRegression()

In [10]:
y_pred = linear_model.predict(x_test)

In [11]:
r2_score(y_test, y_pred)

0.9553063138044949

# **Logistic Regression Model**

In [12]:
df = pd.read_csv("diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [13]:
df.shape

(768, 9)

In [14]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [15]:
x, y = df.iloc[:, :-1], df.iloc[:, -1]

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression()

In [18]:
logistic_model.fit(x_train, y_train)

c:\Users\Bhautik Gondaliaya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [19]:
y_pred = logistic_model.predict(x_test)

In [20]:
confusion_matrix(y_test, y_pred)

array([[121,  30],
       [ 30,  50]])

In [21]:
accuracy_score(y_test, y_pred)

0.7402597402597403

# **Decision Tree Model**

In [23]:
from sklearn.tree import DecisionTreeClassifier

dtc_model = DecisionTreeClassifier()

In [24]:
dtc_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [25]:
y_pred = dtc_model.predict(x_test)

In [26]:
confusion_matrix(y_test, y_pred)

array([[107,  44],
       [ 26,  54]])

In [27]:
accuracy_score(y_test, y_pred)

0.696969696969697

# **Random Forest Model**

In [28]:
from sklearn.ensemble import RandomForestClassifier

rfc_model = RandomForestClassifier()

In [29]:
rfc_model.fit(x_train, y_train)

RandomForestClassifier()

In [30]:
y_pred = rfc_model.predict(x_test)

In [31]:
confusion_matrix(y_test, y_pred)

array([[124,  27],
       [ 28,  52]])

In [32]:
accuracy_score(y_test, y_pred)

0.7619047619047619

# **Naive Bayes Model**

* For continuous data (e.g., normally distributed), use GaussianNB
* For discrete data (e.g., counts or text features), use MultinomialNB
* For binary/boolean features, use BernoulliNB

In [34]:
from sklearn.naive_bayes import BernoulliNB

nb_model = BernoulliNB()

In [35]:
nb_model.fit(x_train, y_train)

BernoulliNB()

In [36]:
y_pred = nb_model.predict(x_test)

In [ ]:
confusion_matrix(y_test, y_pred)

array([[151,   0],
       [ 80,   0]])

In [39]:
accuracy_score(y_test, y_pred)

0.6536796536796536