In [2]:
!nvidia-smi

Thu Jan 23 12:51:00 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
import torch

# Tensor -> datatype (simmiler to numpy but numpy not run on the gpu)

In [9]:
from torch import tensor
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5])
ten = tensor([1,2,3,4,5])
ten, arr

(tensor([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [25]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [26]:
x1 = tensor([1,2,3]).to(device)
x2 = tensor([4,5,6]).to(device)

In [27]:
print(f"Broadcasting value 10 to all elements: {x1+10}")
print(f"element wise addition: {x1+x2}")
print(f"element wise substraction: {x1-x2}")
print(f"element wise multiplication: {x1*x2}")

Broadcasting value 10 to all elements: tensor([11, 12, 13], device='cuda:0')
element wise addition: tensor([5, 7, 9], device='cuda:0')
element wise substraction: tensor([-3, -3, -3], device='cuda:0')
element wise multiplication: tensor([ 4, 10, 18], device='cuda:0')


In [63]:
x3 = tensor([[1,2,3],
            [-4,5,6]]).to(device)

x4 = tensor([[7,8,9],
            [18,11,12]]).to(device)

x5 = tensor([[10,10,10]]).to(device)

x3.shape, x4.shape, x5.shape, x3[1, 0]

(torch.Size([2, 3]),
 torch.Size([2, 3]),
 torch.Size([1, 3]),
 tensor(-4, device='cuda:0'))

In [64]:
x3+x4, x3*x4, x3*x5

(tensor([[ 8, 10, 12],
         [14, 16, 18]], device='cuda:0'),
 tensor([[  7,  16,  27],
         [-72,  55,  72]], device='cuda:0'),
 tensor([[ 10,  20,  30],
         [-40,  50,  60]], device='cuda:0'))

In [65]:
x3.flatten()

tensor([ 1,  2,  3, -4,  5,  6], device='cuda:0')

# Auto Differntiation in Pytorch

* x = 3a^3 - b^2
* dx/da = 9a^2
* dx/db = -2b

In [66]:
a = tensor([1,2,3], dtype=torch.float, requires_grad=True)
b = tensor([4,5,6], dtype=torch.float, requires_grad=True)

In [68]:
x = 3*a**3 - b**2
# dx/da = [9, 36, 81]
# dx/db = [-8, -10, -12]

In [74]:
dummy = torch.ones_like(x) # create tensor like [1.,1.,1.]
x.backward(gradient=dummy) # find diff to the backward propogation using greadient decent technique

In [75]:
a.grad, b.grad

(tensor([ 9., 36., 81.]), tensor([ -8., -10., -12.]))

In [83]:
x = tensor([5], dtype=torch.float, requires_grad=True)

Q = torch.cos(x) + 1/(1+torch.exp(x))
# dQ/dx = -sin(x) + 1/(1+e^x)

In [84]:
dummmy = torch.ones_like(x)

In [85]:
Q.backward(gradient=dummmy)

In [86]:
x.grad

tensor([0.9523])