Author:- **Bhautik Gondaliya**

mo. no.:- **[9586280240](https://)**

mail id.:- **[mr.genius0180@gmail.com](https://)**
>
>
guide:- **Aryan Raj**

Sponcerd:- **Intellipaat**
>
>
Title:- **Module-4 Case-Study Numpy**

Date:- **31/08/2024**

>

In [1]:
import numpy as np

Q1. Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric value and returns a NumPy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return

        [ [5, 5, 5],
          [5, 5, 5],
          [5, 5, 5] ]

In [4]:
def dimentionArray(t1, num):

    arr1 = np.full(t1, num)
    return arr1

dim_tuple = int(input("Enter your row number: ")), int(input("Enter your column number: "))
value = int(input("Enter of Value: "))

dimentionArray(dim_tuple, value)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

>

Q2. Create a method that takes n NumPy arrays of the same dimensions,
sums them and returns the answer.

In [3]:
def nDimentionSum(*arrays):

    if not all(array.shape == arrays[0].shape for array in arrays):
        raise ValueError("All arrays must have the same dimensions.")
    
    return np.sum(arrays, axis=0)

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([[13, 14, 15], [16, 17, 18]])

print(nDimentionSum(a, b, c))

[[21 24 27]
 [30 33 36]]


>

Q3. Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix, e.g:

        [ [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9] ]

top_left_sub_matrix (matrix, 2, 2) -> should return:

        [ [1, 2],
          [4, 5] ]

In [14]:
def subMatrix(matrix, r, c):

        if r > matrix.shape[0] or c > matrix.shape[1]:
                raise ValueError("Submatrix dimensions exceed the dimensions of the input matrix.")
    
        return matrix[:r, :c]

arr1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
r, c = int(input("Enter your row number: ")), int(input("Enter your column number: "))

print(subMatrix(arr1, r, c))


[[1 2]
 [4 5]]


>

Q4. Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the bottom-right N X M sub matrix, e.g:

        [ [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9] ]

sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
        
        [ [5, 6]
          [8, 9] ]


In [15]:
def subMatrix(matrix, r, c):

        if r > matrix.shape[0] or c > matrix.shape[1]:
                raise ValueError("Submatrix dimensions exceed the dimensions of the input matrix.")
    
        return matrix[-r:, -c:]

arr1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
r, c = int(input("Enter your row number: ")), int(input("Enter your column number: "))

print(subMatrix(arr1, r, c))


[[5 6]
 [8 9]]


>

Q5. Given a 1 D NumPy Array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values: [1, 1, 1]
solution(arr) -> should return : {'mean': 1.0, 'std_dev': 0.0}

In [24]:
def calMeanStd(arr):

    mean_val = np.mean(arr)
    std_dev = np.std(arr)

    return {"mean": float(mean_val), "std_dev": float(std_dev)}

arr1 = np.array([1,1,1])
print(calMeanStd(arr1))

{'mean': 1.0, 'std_dev': 0.0}
