Author:- **Bhautik Gondaliya**

mo. no.:- **[9586280240](https://)**

mail id.:- **[mr.genius0180@gmail.com](https://)**
>
>
guide:- **Aryan Raj**

Sponcerd:- **Intellipaat**
>
>
Title:- **Module-4 Assignment Numpy**

Date:- **30/08/2024**

>

In [1]:
import numpy as np

Q1. Create a 3x3 matrix array with values ranging from 2 to 10.

In [6]:
arr1 = np.arange(2, 11).reshape((3,3))
print(arr1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


>

Q2. Create a NumPy array having user input values and convert the integer type to the float type of the elements of the array. For instance: Original array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]

In [17]:
l1 = input("Enter numbers separated by spaces: ")

l1 = l1.split()

try:
    arr1 = np.array(l1).astype(float)
    print(arr1)

except ValueError:
    print("Please enter valid numbers separated by spaces.")

[1. 2. 3. 4. 5.]


>

Q3. Write a NumPy program to append values to the end of an array. For instance: Original array: [10, 20, 30] . After that, append values to the end of the array: [10 20 30 40 50 60 70 80 90]

In [18]:
original_arr = np.array([10, 20, 30])

append_arr = np.append(original_arr, [40, 50, 60, 70, 80, 90])

append_arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

>

Q4. Create two NumPy arrays and add the elements of both the arrays and
store the result in sumArray.

In [19]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([100, 200, 300])

sum_array = np.add(arr1, arr2)
sum_array

array([110, 220, 330])

>

Q5. Create a 3x3 array having values from 10-90 (interval of 10) and store that in array1 Perform the following tasks:

        a. Extract the 1st row from the array
        b. Extract the last element from the array

In [37]:
arr1 = np.arange(10, 100, 10).astype(int).reshape(3,3)
# arr1 = np.linspace(10, 90, 9).astype(int).reshape(3,3)

print("Full Array: \n", arr1)
print("\n1st row of the Array: ", arr1[0])
print("Last elemnent of the Array: ", arr1[-1, -1])

Full Array: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

1st row of the Array:  [10 20 30]
Last elemnent of the Array:  90
